### ISSUE TITLE
new pip 10.0 breaks installation

### ISSUE THREAD

**Issue by booxter** [Marigold/universal-portfolios#13]
```
Collecting universal-portfolios (from ct==0.2.5.dev1)
  Downloading https://files.pythonhosted.org/packages/14/3d/067eda364ed7c5cb89a3caab2973d62c0614d8284b6125907f7e5bdf52d2/universal-portfolios-0.3.2.tar.gz (3.7MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6V_jgj/universal-portfolios/setup.py", line 3, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
```

**Comment by booxter** [comment]
Some details about the root cause of the issue here: https://stackoverflow.com/questions/49837301/pip-10-no-module-named-pip-req

Basically, pip 10.0 intentionally broke everyone who imported the module because it's not supposed to be used programmatically by external dependencies.
